version: "2"
services:

  kong-database:
    image: postgres:9.4
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  kong:
    image: mashape/kong
    restart: always
    depends_on:
      - kong-database
    links:
      - kong-database:kong-database
    security_opt:
      - seccomp:unconfined
    ports:
      - 8000
      - 8443
      - 8001
    expose:
      - "7946"
      - "7946/udp"
    environment:
      - DATABASE=postgres

