version: "2"
services:

  kong-database:
    image: postgres:9.4
    ports:
      - 5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - REPLICATION_MODE=master
      - REPLICATION_USER=replicator
      - REPLICATION_PASS=replpassword

  kong-database-slave:
    image: postgres:9.4
    restart: always
    depends_on:
      - kong-database
    links:
      - kong-database:master
    ports:
      - 5432
    environment:
      - REPLICATION_MODE=slave
      - REPLICATION_HOST=master
      - REPLICATION_USER=replicator
      - REPLICATION_PASS=replpassword

  kong:
    image: mashape/kong
    restart: always
    depends_on:
      - kong-database
    links:
      - kong-database:kong-database
    ports:
      - 8000
      - 8443
      - 8001
    expose:
      - 7946
      - 7946/udp
    environment:
      - DATABASE=postgres
