version: "2"
services:

  kong-database:
    image: postgres:9.4
    ports:
      - 5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  kong:
    image: mashape/kong
    restart: always
    depends_on:
      - kong-database
    links:
      - kong-database:kong-database
    ports:
      - 8000
      - 8443
      - 8001
    expose:
      - 7946
      - 7946/udp
    environment:
      - DATABASE=postgres
      - SERVICE_NAME=kong

  consul:
    image: progrium/consul
    command: -server -bootstrap -ui-dir /ui
    ports:
      - 8500:8500
    expose:
      - 8300
      - 8301/udp
      - 8400
      - 8600
      - 8600/udp

  registrator:
    image: gliderlabs/registrator
    command: consul://consul:8500
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  load-balancer:
    build: .
    restart: always
    container_name: load-balancer
    depends_on:
      - consul
    links:
      - consul:consul
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
    environment:
      - CONSUL_URL=consul:8500
